project_name: serenity
builds:
  - id: main
    main: ./cmd/serenity
    flags:
      - -v
      - -trimpath
    ldflags:
      - -X github.com/sagernet/serenity/constant.Version={{ .Version }} -s -w -buildid=
    env:
      - CGO_ENABLED=0
    targets:
      - linux_386
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_7
      - linux_s390x
      - linux_riscv64
    mod_timestamp: '{{ .CommitTimestamp }}'
snapshot:
  name_template: "{{ .Version }}.{{ .ShortCommit }}"
archives:
  - id: archive
    builds:
      - main
      - android
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
nfpms:
  - id: package
    package_name: serenity
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    homepage: https://serenity.sagernet.org/
    maintainer: nekohasekai <contact-git@sekai.icu>
    description: The configuration generator for sing-box.
    license: GPLv3 or later
    formats:
      - deb
      - rpm
      - archlinux
    priority: extra
    contents:
      - src: release/config/config.json
        dst: /etc/serenity/config.json
        type: config
      - src: release/config/serenity.service
        dst: /usr/lib/systemd/system/serenity.service
      - src: release/config/serenity@.service
        dst: /usr/lib/systemd/system/serenity@.service
      - src: LICENSE
        dst: /usr/share/licenses/serenity/LICENSE
    deb:
      signature:
        key_file: "{{ .Env.NFPM_KEY_PATH }}"
      fields:
        Bugs: https://github.com/SagerNet/serenity/issues
    rpm:
      signature:
        key_file: "{{ .Env.NFPM_KEY_PATH }}"
source:
  enabled: false
  name_template: '{{ .ProjectName }}-{{ .Version }}.source'
  prefix_template: '{{ .ProjectName }}-{{ .Version }}/'
checksum:
  disable: true
  name_template: '{{ .ProjectName }}-{{ .Version }}.checksum'
signs:
  - artifacts: checksum
release:
  github:
    owner: SagerNet
    name: serenity
  name_template: '{{ if .IsSnapshot }}{{ nightly }}{{ else }}{{ .Version }}{{ end }}'
  draft: true
  mode: replace
